### PR TITLE
[Runner] Reduce the docker-driver's CC.

### PR DESCRIPTION
**Pull request by BlaCkinkGJ**
To reduce the CC(Cyclomatic-Complexity) of docker-driver, I extracted the local docker image
creation part.

### CODE REVIEW

**Comment by SuhoSon** [comment]
I think the below codes should be added to docker_create_local_image().
Because local image means an image with a local trace-replay binary.

``` c
        cmd = (char *)malloc(PAGE_SIZE * PAGE_SIZE);
        if (!cmd) {
                ret = -ENOMEM;
                goto exception;
        }

        sprintf(cmd, "docker cp %s new_trace_replay:/usr/local/bin/",
                global_info_head->trace_replay_path);
        ret = system(cmd);
        if (ret) {
                pr_info(ERROR, "Cannot copy trace_replay binary.\n");
                goto exception;
        }

        ret = system(
                "docker commit new_trace_replay suhoson/trace_replay:local");
        if (ret) {
                pr_info(ERROR, "Cannot commit new image.\n");
                goto exception;
        }

        ret = system("docker rm -f new_trace_replay");
```

**Comment by BlaCkinkGJ** [comment]
Ok, I will check and add it.

**Comment by BlaCkinkGJ** [comment]
@SuhoSon I fixed what you said before. Please check and re-review it.

**Review by SuhoSon — COMMENTED** [review]
Confirm.

**Pull request merged**
